[versions]
kotlin = "[2.1,3.0)"
ktlint = "[12.1,13.0)"
shadow = "[8.3,9.0)"
jreleaser = "[1.16,2.0)"
kotlinxSerializationJson = "[1.7,2.0)"
mongodb = "5.2.1"
jackson = "[2.18,3.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

mongodb-bson = { group = "org.mongodb", name = "bson", version.ref = "mongodb" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
